// Всички спрайтове – рисувани в кода (собствена пикселна графика).
// Всеки спрайт се строи веднъж в малко canvas; има и огледално копие.

const PAL = {
  k: '#101018', // контур
  g: '#40d040',
  l: '#f8f0b0',
  w: '#ffffff',
  W: '#d8d8e8', // сенчесто бяло
  y: '#ffe040',
  o: '#ff9020',
  r: '#e83838',
  R: '#901828',
  p: '#ff78c8',
  P: '#c03890',
  m: '#b070ff',
  M: '#7040c0',
  b: '#40a0ff',
  B: '#2060c0',
  c: '#60f0f0',
  n: '#a06030',
  N: '#603818',
  s: '#b0b0c0',
  S: '#707088',
};

function makeCanvas(w, h) {
  const c = document.createElement('canvas');
  c.width = w; c.height = h;
  return c;
}

function flip(src) {
  const c = makeCanvas(src.width, src.height);
  const g = c.getContext('2d');
  g.translate(src.width, 0);
  g.scale(-1, 1);
  g.drawImage(src, 0, 0);
  return c;
}

// ascii → {r: canvas надясно, l: canvas наляво}
function build(rows, pal = {}) {
  const h = rows.length;
  const w = Math.max(...rows.map(r => r.length));
  const c = makeCanvas(w, h);
  const g = c.getContext('2d');
  rows.forEach((row, y) => {
    for (let x = 0; x < row.length; x++) {
      const ch = row[x];
      if (ch === '.' || ch === ' ') continue;
      g.fillStyle = pal[ch] || PAL[ch] || '#f0f';
      g.fillRect(x, y, 1, 1);
    }
  });
  return { r: c, l: flip(c) };
}

function art(str) {
  return str.trim().split('\n').map(s => s.trim());
}

// ─── Дракончета ─────────────────────────────────────────────
const DRAGON_BODY = art(`
......kkkkk.....
....kkgggggkk...
...kgggggwwwgk..
..kggggwwwwkwk..
.kyggggwwwwkwgk.
kyyggggwwwwwwggk
kyggggggwwwwgggk
.kyggggggggggggk
.kygglllllgggkk.
kyyglllllllggk..
kyggllllllllgk..
.kgglllllllggk..
..kgglllllggk...
`);
const FEET_A = art(`
...kgggkgggk....
..kooook.kook...
..kkkkk..kkkk...
`);
const FEET_B = art(`
...kgggkgggk....
...kooookook....
...kkkkkkkkk....
`);
const FEET_JUMP = art(`
...kggggggk.....
....kookook.....
....kkk.kkk.....
`);
const SHOOT_HEAD = art(`
......kkkkk.....
....kkgggggkk...
...kgggggwwwgk..
..kggggwwwwkwk..
.kyggggwwwwkwgkk
kyyggggwwwwwwgrk
kyggggggwwwwgrr.
.kyggggggggggkkk
.kygglllllgggkk.
kyyglllllllggk..
kyggllllllllgk..
.kgglllllllggk..
..kgglllllggk...
`);
const DEAD = art(`
......kkkkk.....
....kkgggggkk...
...kgggggggggk..
..kgggkgkgggggk.
.kyggggkggkgkgk.
kyyggggkgggkgggk
kyggggkgkgkgkggk
.kyggggggggggggk
.kygglllllgggkk.
kyyglllllllggk..
kyggllllllllgk..
.kgglllllllggk..
..kgglllllggk...
...kgggkgggk....
..kooook.kook...
..kkkkk..kkkk...
`);

function dragonSet(body, belly, spikes) {
  const pal = { g: body, l: belly, y: spikes };
  return {
    stand: build([...DRAGON_BODY, ...FEET_A], pal),
    walk: build([...DRAGON_BODY, ...FEET_B], pal),
    jump: build([...DRAGON_BODY, ...FEET_JUMP], pal),
    shoot: build([...SHOOT_HEAD, ...FEET_A], pal),
    dead: build(DEAD, pal),
  };
}

// ─── Врагове ────────────────────────────────────────────────
const E_WINDUP = art(`
.......kk.......
......kyyk......
.......kk.......
....kkkkkkkk....
...kwwwwwwwwk...
..kwwwwwwwwwwk..
..kwwwwwkkwkkk..
..kwwwwwkbwkbk..
..kwwwwwwwwwwk..
..kwwwwwwkkkkk..
..kwwwwwwwwwwk..
..kWwwwwwwwwwk..
...kWWwwwwwWk...
....kkkkkkkk....
...kook.kook....
...kkkk.kkkk....
`);
const E_WINDUP2 = art(`
.......kk.......
.....kyyyyk.....
.......kk.......
....kkkkkkkk....
...kwwwwwwwwk...
..kwwwwwwwwwwk..
..kwwwwwkkwkkk..
..kwwwwwkbwkbk..
..kwwwwwwwwwwk..
..kwwwwwwkkkkk..
..kwwwwwwwwwwk..
..kWwwwwwwwwwk..
...kWWwwwwwWk...
....kkkkkkkk....
....kookkook....
....kkkkkkkk....
`);
const E_SPRING = art(`
................
.....kkkkkk.....
....kggggggk....
...kggggwwgwk...
...kggggwkgwk...
...kggggggggk...
...kggggkkkkk...
....kggggggk....
.....kkkkkk.....
......kssk......
.....kssssk.....
......kssk......
.....kssssk.....
......kssk......
....kkkkkkkk....
....kSSSSSSk....
`);
const E_SPRING2 = art(`
................
................
................
.....kkkkkk.....
....kggggggk....
...kggggwwgwk...
...kggggwkgwk...
...kggggggggk...
...kggggkkkkk...
....kggggggk....
.....kkkkkk.....
.....kssssk.....
......kssk......
.....kssssk.....
....kkkkkkkk....
....kSSSSSSk....
`);
const E_GHOST = art(`
................
.....kkkkkk.....
...kkmmmmmmkk...
..kmmmmmmmmmmk..
.kmmmmmmwwmmwwk.
.kmmmmmmwkmmwkk.
kmmmmmmmwkmmwkmk
kmmmmmmmmmmmmmmk
kmmmmmmmmkkkkmmk
kMmmmmmmmmmmmmmk
kMmmmmmmmmmmmmmk
.kMmmmmmmmmmmmk.
.kMMmkmmmkmmmkk.
..kkk.kmk.kmk...
.......k...k....
................
`);
const E_GHOST2 = art(`
................
.....kkkkkk.....
...kkmmmmmmkk...
..kmmmmmmmmmmk..
.kmmmmmmwwmmwwk.
.kmmmmmmwkmmwkk.
kmmmmmmmwkmmwkmk
kmmmmmmmmmmmmmmk
kmmmmmmmmkkkkmmk
kMmmmmmmmmmmmmmk
kMmmmmmmmmmmmmmk
.kMmmmmmmmmmmmk.
.kMmkmmmkmmmkmk.
..k.kmk.kmk.kk..
.....k...k......
................
`);
const E_WIZARD = art(`
......kkkk......
....kkwwwwkk....
...kwwwwwwwwk...
..kwwwwwwwwwwk..
..kwwwwwkkwkkk..
..kwwwwwkrwkrk..
..kwwwwwwwwwwk..
.kwwwwwwwwwwwwk.
.kwwwwwwwwwwwwk.
kWwwwwwwwwwwwwwk
kWwwwwwwwwwwwwwk
kWWwwwwwwwwwwwwk
.kWWwwwwwwwwwwk.
.kWwkwwwkwwwkwk.
..kk.kkk.kkk.kk.
................
`);
const E_WIZARD2 = art(`
......kkkk......
....kkwwwwkk....
...kwwwwwwwwk...
..kwwwwwwwwwwk..
..kwwwwwkkwkkk..
..kwwwwwkrwkrk..
..kwwwwwwwwwwk..
.kwwwwwwwwwwwwk.
.kwwwwwwwwwwwwk.
kWwwwwwwwwwwwwwk
kWwwwwwwwwwwwwwk
kWWwwwwwwwwwwwwk
.kWWwwwwwwwwwwk.
.kkwwkwwwkwwwkk.
...kk.kkk.kkk...
................
`);
const E_FIRE = art(`
................
.....kkkkkk.....
....kooooook....
...kooooooook...
..koooowwoowwk..
..kooooowkowkk..
..koooooooooook.
..koooookkkkkkk.
..kooooookrrrk..
..kooooooookkk..
..kooooooooook..
.kNoooooooooook.
.kNNoooooooooNk.
..kNNoookoooNk..
..kkkkk..kkkkk..
................
`);
const E_FIRE2 = art(`
................
.....kkkkkk.....
....kooooook....
...kooooooook...
..koooowwoowwk..
..kooooowkowkk..
..koooooooooook.
..koooookkkkkkk.
..koooooooooook.
..kooooooooook..
..kooooooooook..
.kNoooooooooook.
.kNNoooooooooNk.
..kNNoookoooNk..
...kkkk..kkkk...
................
`);
const E_PROP = art(`
...kkkkkkkkkk...
......kyyk......
.......kk.......
.....kkkkkk.....
...kkppppppkk...
..kppppppppppk..
..kppppppwwpwwk.
.kpppppppwkpwkk.
.kPpppppppppppk.
.kPppppppprrrpk.
.kPPpppppppppk..
..kPPppppppppk..
...kkPPpppPkk...
.....kkkkkk.....
................
................
`);
const E_PROP2 = art(`
......kkkk......
......kyyk......
.......kk.......
.....kkkkkk.....
...kkppppppkk...
..kppppppppppk..
..kppppppwwpwwk.
.kpppppppwkpwkk.
.kPpppppppppppk.
.kPppppppprrrpk.
.kPPpppppppppk..
..kPPppppppppk..
...kkPPpppPkk...
.....kkkkkk.....
................
................
`);
const E_SKULL = art(`
.....kkkkkk.....
...kkwwwwwwkk...
..kwwwwwwwwwwk..
.kwwwwwwwwwwwwk.
.kwwkkkwwkkkwwk.
kwwkkrkwwkrkkwwk
kwwkkkkwwkkkkwwk
kwwwwwwkkwwwwwwk
kWwwwwwwwwwwwwWk
.kWwkwkwkwkwkWk.
.kWwwwwwwwwwwWk.
..kWWwwwwwwWWk..
...kkWWWWWWkk...
.....kkkkkk.....
................
................
`);

// Ядосан вариант – същата рисунка с червеникава палитра.
const ANGRY = { w: '#ff9090', W: '#e05050', g: '#ff6060', m: '#ff5080', M: '#b02050', o: '#ff4040', N: '#901010', p: '#ff4060', P: '#a01030', s: '#ffb0b0', S: '#c06060' };

function enemySet(a, b) {
  return {
    frames: [build(a), build(b)],
    angry: [build(a, ANGRY), build(b, ANGRY)],
  };
}

// ─── Балончета (генерирани по формула) ─────────────────────
function bubbleCanvas(ring, fill, fillAlpha = 0.28) {
  const c = makeCanvas(16, 16);
  const g = c.getContext('2d');
  for (let y = 0; y < 16; y++) {
    for (let x = 0; x < 16; x++) {
      const d = Math.hypot(x - 7.5, y - 7.5);
      if (d <= 7.6 && d > 6.1) { g.globalAlpha = 1; g.fillStyle = ring; g.fillRect(x, y, 1, 1); }
      else if (d <= 6.1) { g.globalAlpha = fillAlpha; g.fillStyle = fill; g.fillRect(x, y, 1, 1); }
    }
  }
  g.globalAlpha = 1;
  g.fillStyle = '#fff';
  g.fillRect(4, 3, 2, 1); g.fillRect(3, 4, 1, 2); g.fillRect(4, 4, 1, 1);
  return c;
}

function pix(g, rows, ox, oy) {
  rows.forEach((row, y) => {
    for (let x = 0; x < row.length; x++) {
      const ch = row[x];
      if (ch === '.') continue;
      g.fillStyle = PAL[ch] || ch;
      g.fillRect(ox + x, oy + y, 1, 1);
    }
  });
}

function specialBubble(ring, icon) {
  const c = bubbleCanvas(ring, ring, 0.35);
  pix(c.getContext('2d'), art(icon), 4, 4);
  return c;
}

const ICON_BOLT = `
...yy..
..yy...
.yyyyy.
...yy..
..yy...
.yy....
`;
const ICON_FIRE = `
...r...
..rr.r.
.rorrr.
.royorr
.royyor
..rooo.
`;
const ICON_WATER = `
...b...
..bb...
.bbwb..
.bbbwb.
.bbbbb.
..bbb..
`;

// ─── Предмети (плодове и бонуси) – пикселни картинки 16×16 ───
const ITEM_ART = {
  cherry: `
..........kk....
.........kgk....
........kgk.....
.......kgkgk....
......kgk..gk...
.....kgk....gk..
...kkkk....kkkk.
..krrwrk..krrwrk
..krrrwk..krrrrk
..krrrrk..krrrrk
..kRrrrk..kRrrrk
...kkkk....kkkk.
`,
  banana: `
...........kk...
..........kyk...
..........kyyk..
..........kyyk..
.........kyyyk..
........kyyyk...
.......kyyyyk...
.....kkyyyyk....
..kkkyyyyykk....
.kyyyyyyykk.....
..kkkkkkk.......
`,
  orange: `
.......kk.......
.....kkgkk......
....kgggk.......
...kkookkkk.....
..kooooooook....
.kooooooooyok...
.kooooooooyok...
.koooooooooook..
.koooooooooook..
.koooooooooook..
..kooooooooook..
...koooooooook..
....kkkkkkkkk...
`,
  melon: `
................
................
..kkkkkkkkkkkk..
.kgggggggggggggk
.kwwwwwwwwwwwwwk
..krrrrkrrkrrrk.
..krrkrrrrrrkrk.
...krrrrkrrrrk..
....krrrrrrrk...
.....kkrrrkk....
.......kkk......
`,
  grapes: `
.......kgk......
.......kgk......
....kkkkkkkkk...
...kmmkmmkmmk...
...kmwkmwkmwk...
....kkmmkmmkk...
....kmwkmwkmk...
.....kkmmkkk....
.....kmwkmwk....
......kkmmk.....
.......kmwk.....
........kk......
`,
  cake: `
.......kk.......
......krrk......
.......kk.......
...kkkkkkkkkk...
..kwwwwwwwwwwk..
..kwpwwpwwpwwk..
..kpppppppppppk.
..knnnnnnnnnnk..
..kyyyyyyyyyyk..
..knnnnnnnnnnk..
..kkkkkkkkkkkk..
`,
  diamond: `
................
....kkkkkkkk....
...kcwccwccwk...
..kccwccwcccck..
.kkkkkkkkkkkkkk.
..kcccwcccwcck..
...kcccwccwck...
....kcccwcck....
.....kccwck.....
......kcck......
.......kk.......
`,
  icecream: `
.....kkkkk......
....kpppwpk.....
...kpppppppk....
...kpppppppk....
...kwwwwwwwk....
....kyykyyk.....
....kyyyykk.....
.....kykyk......
.....kyyyk......
......kyk.......
......kyk.......
.......k........
`,
  candyPink: `
................
................
.kk.........kk..
kppk..kkkk..kppk
kpppkkpwppkkpppk
kppppppppppppppk
kpppkkppppkkpppk
kppk..kkkk..kppk
.kk.........kk..
`,
  candyBlue: `
................
................
.kk.........kk..
kbbk..kkkk..kbbk
kbbbkkbwbbkkbbbk
kbbbbbbbbbbbbbbk
kbbbkkbbbbkkbbbk
kbbk..kkkk..kbbk
.kk.........kk..
`,
  candyYellow: `
................
................
.kk.........kk..
kyyk..kkkk..kyyk
kyyykkywyykkyyyk
kyyyyyyyyyyyyyyk
kyyykkyyyykkyyyk
kyyk..kkkk..kyyk
.kk.........kk..
`,
  shoe: `
................
................
.....kkkkk......
.....kbbbk......
.....kbwbk......
.....kbbbkk.....
.....kbbbbbkk...
....kbbbbwbbbk..
...kbbbbbbbbbbk.
..kwwwwwwwwwwwk.
..kkkkkkkkkkkkk.
`,
  umbrella: `
.......kk.......
.....kkppkk.....
...kkpppppwkk...
..kppppppppwpk..
.kppppppppppwpk.
.kpppppppppppppk
.kkpkkpkkpkkpkk.
.......kk.......
.......kk.......
.......kk.......
....kk.kk.......
....kkkkk.......
`,
  clock: `
.....kkkkkk.....
...kkwwwwwwkk...
..kwwwwkwwwwwk..
.kwwwwwkwwwwwwk.
.kwwwwwkwwwwwwk.
.kwwwwwkkkkkwwk.
.kwwwwwwwwwwwwk.
.kwwwwwwwwwwwwk.
..kwwwwwwwwwwk..
...kkwwwwwwkk...
....rkkkkkkr....
...rr......rr...
`,
  bomb: `
..........y.....
.........yoy....
.........ky.....
........kk......
.....kkkkkk.....
...kkSSSSSSkk...
..kSSwSSSSSSSk..
..kSwSSSSSSSSk..
.kSSSSSSSSSSSSk.
.kSSSSSSSSSSSSk.
.kSSSSSSSSSSSSk.
..kSSSSSSSSSSk..
...kkSSSSSSkk...
.....kkkkkk.....
`,
  potion: `
......kkkk......
......kwwk......
.......kk.......
......kwwk......
.....kwbbbk.....
....kbbwbbbk....
...kbbbwbbbbk...
...kbbbbbbbbk...
...kbbbbbbbbk...
...kBbbbbbbBk...
....kBBBBBBk....
.....kkkkkk.....
`,
};

function itemCanvas(str) {
  const rows = art(str);
  const c = makeCanvas(16, 16);
  pix(c.getContext('2d'), rows, 0, 16 - rows.length);
  return c;
}

// ─── Шефът (48×48, рисуван с примитиви и изчистен до пиксели) ─
function bossCanvas(body, dark) {
  const c = makeCanvas(48, 48);
  const g = c.getContext('2d');
  const disk = (x, y, r, col) => {
    g.fillStyle = col;
    for (let yy = Math.floor(y - r); yy <= y + r; yy++)
      for (let xx = Math.floor(x - r); xx <= x + r; xx++)
        if (Math.hypot(xx + 0.5 - x, yy + 0.5 - y) <= r) g.fillRect(xx, yy, 1, 1);
  };
  disk(24, 26, 21, '#101018');
  disk(24, 26, 20, body);
  disk(24, 34, 13, dark);
  // очи
  disk(15, 18, 6, '#101018'); disk(15, 18, 5, '#fff'); disk(17, 19, 2.2, '#101018');
  disk(33, 18, 6, '#101018'); disk(33, 18, 5, '#fff'); disk(35, 19, 2.2, '#101018');
  // зли вежди
  g.fillStyle = '#101018';
  for (let i = 0; i < 8; i++) { g.fillRect(9 + i, 10 + (i >> 1), 1, 2); g.fillRect(38 - i, 10 + (i >> 1), 1, 2); }
  // уста
  g.fillStyle = '#101018'; g.fillRect(14, 30, 20, 7);
  g.fillStyle = '#e83838'; g.fillRect(15, 31, 18, 5);
  g.fillStyle = '#fff';
  for (let i = 0; i < 4; i++) { g.fillRect(16 + i * 5, 31, 3, 2); g.fillRect(18 + i * 4, 34, 2, 2); }
  // корона
  g.fillStyle = '#101018'; g.fillRect(13, 2, 22, 6);
  g.fillStyle = '#ffe040'; g.fillRect(14, 3, 20, 4);
  for (let i = 0; i < 3; i++) { g.fillStyle = '#101018'; g.fillRect(14 + i * 9, -1 + 0, 4, 3); g.fillStyle = '#ffe040'; g.fillRect(15 + i * 9, 0, 2, 3); }
  g.fillStyle = '#e83838'; g.fillRect(23, 4, 2, 2);
  return c;
}

export const SPR = {};

export function buildSprites() {
  SPR.p1 = dragonSet('#40d040', '#f8f0b0', '#f0f0f0');
  SPR.p2 = dragonSet('#40a0ff', '#f8f0b0', '#f0f0f0');
  SPR.enemies = {
    windup: enemySet(E_WINDUP, E_WINDUP2),
    spring: enemySet(E_SPRING, E_SPRING2),
    ghost: enemySet(E_GHOST, E_GHOST2),
    wizard: enemySet(E_WIZARD, E_WIZARD2),
    fire: enemySet(E_FIRE, E_FIRE2),
    prop: enemySet(E_PROP, E_PROP2),
  };
  SPR.skull = build(E_SKULL);
  SPR.bubble = {
    p1: bubbleCanvas('#40e040', '#80ff80'),
    p2: bubbleCanvas('#40a0ff', '#80c0ff'),
    warn: bubbleCanvas('#ffe040', '#ffe080'),
    danger: bubbleCanvas('#ff4040', '#ff8080'),
    white: bubbleCanvas('#ffffff', '#ffffff', 0.5),
    lightning: specialBubble('#ffe040', ICON_BOLT),
    fire: specialBubble('#ff5030', ICON_FIRE),
    water: specialBubble('#40a0ff', ICON_WATER),
    letter: bubbleCanvas('#ff78c8', '#ff78c8', 0.55),
  };
  SPR.items = {};
  for (const [k, v] of Object.entries(ITEM_ART)) SPR.items[k] = itemCanvas(v);
  SPR.boss = bossCanvas('#b070ff', '#8050d0');
  SPR.bossHit = bossCanvas('#ffffff', '#ffd0d0');
  SPR.bossAngry = bossCanvas('#ff5080', '#c02050');
  // Скалата/снарядите
  SPR.rock = build(art(`
..kkkk..
.kssssk.
kssSsssk
ksSsssSk
ksssSssk
.kSsssk.
..kkkk..
`));
  SPR.fireball = build(art(`
..rr....
.royrr..
roywyorr
royyyorr
.roorr..
..rr....
`));
  SPR.bottle = build(art(`
..kk..
..kk..
.kwwk.
kgggwk
kggggk
kggggk
kggggk
.kkkk.
`));
}

export { PAL, art, build };
